/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    DiffPanel: typeof import('./components/diff/DiffPanel.vue')['default']
    FileTreePanel: typeof import('./components/file-tree/FileTreePanel.vue')['default']
    ILucideFiles: typeof import('~icons/lucide/files')['default']
    ILucideGitCompare: typeof import('~icons/lucide/git-compare')['default']
    ILucideMessageSquare: typeof import('~icons/lucide/message-square')['default']
    ILucidePanelLeft: typeof import('~icons/lucide/panel-left')['default']
    ProjectSidebar: typeof import('./components/sidebar/ProjectSidebar.vue')['default']
    ProviderSettings: typeof import('./components/settings/ProviderSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
