/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSelect: typeof import('./components/ui/AppSelect.vue')['default']
    BottomBar: typeof import('./components/BottomBar.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    ChatPanel: typeof import('./components/chat/ChatPanel.vue')['default']
    DiffFileCards: typeof import('./components/diff/DiffFileCards.vue')['default']
    DiffLines: typeof import('./components/diff/DiffLines.vue')['default']
    DiffPanel: typeof import('./components/diff/DiffPanel.vue')['default']
    DiffTabView: typeof import('./components/views/DiffTabView.vue')['default']
    FileTabView: typeof import('./components/views/FileTabView.vue')['default']
    FileTreePanel: typeof import('./components/file-tree/FileTreePanel.vue')['default']
    GitGraphTabView: typeof import('./components/views/GitGraphTabView.vue')['default']
    ILucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    ILucideArrowUp: typeof import('~icons/lucide/arrow-up')['default']
    ILucideCheck: typeof import('~icons/lucide/check')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    ILucideChevronsUpDown: typeof import('~icons/lucide/chevrons-up-down')['default']
    ILucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideFile: typeof import('~icons/lucide/file')['default']
    ILucideFiles: typeof import('~icons/lucide/files')['default']
    ILucideFileWarning: typeof import('~icons/lucide/file-warning')['default']
    ILucideFolder: typeof import('~icons/lucide/folder')['default']
    ILucideGitBranch: typeof import('~icons/lucide/git-branch')['default']
    ILucideGitCompare: typeof import('~icons/lucide/git-compare')['default']
    ILucideInfo: typeof import('~icons/lucide/info')['default']
    ILucideKeyboard: typeof import('~icons/lucide/keyboard')['default']
    ILucideLoaderCircle: typeof import('~icons/lucide/loader-circle')['default']
    ILucideMenu: typeof import('~icons/lucide/menu')['default']
    ILucideMessageSquare: typeof import('~icons/lucide/message-square')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucidePanelLeft: typeof import('~icons/lucide/panel-left')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideSlidersHorizontal: typeof import('~icons/lucide/sliders-horizontal')['default']
    ILucideSquare: typeof import('~icons/lucide/square')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    ProjectSidebar: typeof import('./components/sidebar/ProjectSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./components/settings/SettingsModal.vue')['default']
    TitleBar: typeof import('./components/layout/TitleBar.vue')['default']
    ToolCallCard: typeof import('./components/chat/ToolCallCard.vue')['default']
    WorkspaceTabBar: typeof import('./components/layout/WorkspaceTabBar.vue')['default']
  }
}
