services:
  postgres:
    image: postgres:18.3
    container_name: oct-postgres
    environment:
      POSTGRES_USER: oct
      POSTGRES_PASSWORD: oct
      POSTGRES_DB: oct
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
