/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/conversations/{id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_messages"];
    put?: never;
    post: operations["send_message"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_projects"];
    put?: never;
    post: operations["create_project"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_project"];
    put?: never;
    post?: never;
    delete: operations["delete_project"];
    options?: never;
    head?: never;
    patch: operations["update_project"];
    trace?: never;
  };
  "/api/projects/{projectId}/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_conversations"];
    put?: never;
    post: operations["create_conversation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{projectId}/conversations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["get_conversation"];
    put?: never;
    post?: never;
    delete: operations["delete_conversation"];
    options?: never;
    head?: never;
    patch: operations["update_conversation"];
    trace?: never;
  };
  "/api/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["list_providers"];
    put?: never;
    post: operations["create_provider"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/providers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_provider"];
    post?: never;
    delete: operations["delete_provider"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/providers/{id}/models": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["create_model"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/providers/{providerId}/models/{modelId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations["update_model"];
    post?: never;
    delete: operations["delete_model"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AgentEvent:
      | {
          data: string;
          /** @enum {string} */
          type: "text_delta";
        }
      | {
          data: string;
          /** @enum {string} */
          type: "reasoning_delta";
        }
      | {
          data: {
            arguments: string;
            id: string;
            name: string;
          };
          /** @enum {string} */
          type: "tool_call_start";
        }
      | {
          data: {
            call_id: string;
            content: string;
            is_error: boolean;
          };
          /** @enum {string} */
          type: "tool_result";
        }
      | {
          data: {
            /** Format: int32 */
            input_tokens?: number | null;
            /** Format: int32 */
            output_tokens?: number | null;
            /** Format: int32 */
            reasoning_tokens?: number | null;
          };
          /** @enum {string} */
          type: "usage";
        }
      | {
          /** @enum {string} */
          type: "finish";
        }
      | {
          /** @enum {string} */
          type: "cancelled";
        }
      | {
          data: string;
          /** @enum {string} */
          type: "error";
        };
    Conversation: {
      /** Format: date-time */
      created_at: string;
      id: string;
      project_id: string;
      title: string;
      /** Format: date-time */
      updated_at: string;
    };
    CreateConversationRequest: {
      title?: string | null;
    };
    CreateModelRequest: {
      attachment?: boolean | null;
      /** Format: double */
      cost_cache_read?: number | null;
      /** Format: double */
      cost_cache_write?: number | null;
      /** Format: double */
      cost_input?: number | null;
      /** Format: double */
      cost_output?: number | null;
      family?: string | null;
      knowledge?: string | null;
      /** Format: int64 */
      limit_context?: number | null;
      /** Format: int64 */
      limit_output?: number | null;
      modalities_input?: string | null;
      modalities_output?: string | null;
      model_id: string;
      name: string;
      open_weights?: boolean | null;
      reasoning?: boolean | null;
      release_date?: string | null;
      structured_output?: boolean | null;
      temperature?: boolean | null;
      tool_call?: boolean | null;
    };
    CreateProjectRequest: {
      name: string;
      working_dir: string;
    };
    CreateProviderRequest: {
      api_key: string;
      base_url: string;
      doc_url?: string | null;
      id: string;
      name: string;
    };
    Model: {
      attachment: boolean;
      /** Format: double */
      cost_cache_read?: number | null;
      /** Format: double */
      cost_cache_write?: number | null;
      /** Format: double */
      cost_input?: number | null;
      /** Format: double */
      cost_output?: number | null;
      /** Format: date-time */
      created_at: string;
      family?: string | null;
      id: string;
      is_enabled: boolean;
      knowledge?: string | null;
      /** Format: int64 */
      limit_context?: number | null;
      /** Format: int64 */
      limit_output?: number | null;
      modalities_input?: string | null;
      modalities_output?: string | null;
      model_id: string;
      name: string;
      open_weights: boolean;
      provider_id: string;
      reasoning: boolean;
      release_date?: string | null;
      source: string;
      structured_output: boolean;
      temperature: boolean;
      tool_call: boolean;
    };
    ModelSummary: {
      attachment: boolean;
      /** Format: double */
      cost_input?: number | null;
      /** Format: double */
      cost_output?: number | null;
      family?: string | null;
      is_enabled: boolean;
      /** Format: int64 */
      limit_context?: number | null;
      /** Format: int64 */
      limit_output?: number | null;
      model_id: string;
      name: string;
      reasoning: boolean;
      source: string;
      tool_call: boolean;
    };
    Project: {
      /** Format: date-time */
      created_at: string;
      id: string;
      name: string;
      /** Format: date-time */
      updated_at: string;
      working_dir: string;
    };
    Provider: {
      adapter_type: string;
      base_url?: string | null;
      /** Format: date-time */
      created_at: string;
      doc_url?: string | null;
      id: string;
      name: string;
      source: string;
      /** Format: date-time */
      updated_at: string;
    };
    ProviderResponse: {
      adapter_type: string;
      api_key_set: boolean;
      base_url?: string | null;
      /** Format: date-time */
      created_at: string;
      doc_url?: string | null;
      id: string;
      models: components["schemas"]["ModelSummary"][];
      name: string;
      source: string;
      /** Format: date-time */
      updated_at: string;
    };
    SendMessageRequest: {
      content: string;
      provider_spec?: string | null;
    };
    StoredMessage: {
      conversation_id: string;
      /** Format: date-time */
      created_at: string;
      id: string;
      /** Format: int64 */
      input_tokens?: number | null;
      model_id?: string | null;
      /** Format: int64 */
      ordering: number;
      /** Format: int64 */
      output_tokens?: number | null;
      parts_json: string;
      provider_id?: string | null;
      /** Format: int64 */
      reasoning_tokens?: number | null;
      role: string;
    };
    UpdateConversationRequest: {
      title?: string | null;
    };
    UpdateModelRequest: {
      attachment?: boolean | null;
      /** Format: double */
      cost_cache_read?: number | null;
      /** Format: double */
      cost_cache_write?: number | null;
      /** Format: double */
      cost_input?: number | null;
      /** Format: double */
      cost_output?: number | null;
      family?: string | null;
      is_enabled?: boolean | null;
      knowledge?: string | null;
      /** Format: int64 */
      limit_context?: number | null;
      /** Format: int64 */
      limit_output?: number | null;
      modalities_input?: string | null;
      modalities_output?: string | null;
      name?: string | null;
      open_weights?: boolean | null;
      reasoning?: boolean | null;
      release_date?: string | null;
      structured_output?: boolean | null;
      temperature?: boolean | null;
      tool_call?: boolean | null;
    };
    UpdateProjectRequest: {
      name?: string | null;
      working_dir?: string | null;
    };
    UpdateProviderRequest: {
      api_key?: string | null;
      base_url?: string | null;
      doc_url?: string | null;
      name?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_messages: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Conversation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoredMessage"][];
        };
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  send_message: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Conversation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendMessageRequest"];
      };
    };
    responses: {
      /** @description SSE stream of agent events */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Agent is already running for this conversation */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_projects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"][];
        };
      };
    };
  };
  create_project: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProjectRequest"];
      };
    };
    responses: {
      /** @description Created project */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
    };
  };
  get_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Project"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_project: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProjectRequest"];
      };
    };
    responses: {
      /** @description Project updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_conversations: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        projectId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of conversations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"][];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_conversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        projectId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConversationRequest"];
      };
    };
    responses: {
      /** @description Created conversation */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_conversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        projectId: string;
        /** @description Conversation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Conversation"];
        };
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_conversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        projectId: string;
        /** @description Conversation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_conversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Project ID */
        projectId: string;
        /** @description Conversation ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConversationRequest"];
      };
    };
    responses: {
      /** @description Title updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  list_providers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of providers with their models */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"][];
        };
      };
    };
  };
  create_provider: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateProviderRequest"];
      };
    };
    responses: {
      /** @description Created provider */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProviderResponse"];
        };
      };
      /** @description Provider ID already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_provider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Provider ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateProviderRequest"];
      };
    };
    responses: {
      /** @description Provider updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Provider not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_provider: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Provider ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Provider not found or is builtin */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  create_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Provider ID */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateModelRequest"];
      };
    };
    responses: {
      /** @description Model created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ModelSummary"];
        };
      };
      /** @description Provider not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Model already exists for this provider */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Provider ID */
        providerId: string;
        /** @description Model ID */
        modelId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateModelRequest"];
      };
    };
    responses: {
      /** @description Model updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Model not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  delete_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Provider ID */
        providerId: string;
        /** @description Model ID */
        modelId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Model deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Model not found or is builtin */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
